print("##############################")
print("#                            #")
print("#   Muhammad Fauzan Ahsani   #")
print("#      2310817310009         #")
print("#                            #")
print("##############################")